/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { FeedTest, FeedTestInterface } from "../FeedTest";

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
];

const _bytecode =
  "0x6080604052348015600f57600080fd5b50735f4ec3df9cbd43714fe2740f5e3616155c5b84196000806101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff160217905550603f8060716000396000f3fe6080604052600080fdfea264697066735822122011776ff132ea9e0f8ad943c04d9e5fdfe0d12948225bd0838bae7576ef72d48964736f6c63430008090033";

export class FeedTest__factory extends ContractFactory {
  constructor(
    ...args: [signer: Signer] | ConstructorParameters<typeof ContractFactory>
  ) {
    if (args.length === 1) {
      super(_abi, _bytecode, args[0]);
    } else {
      super(...args);
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<FeedTest> {
    return super.deploy(overrides || {}) as Promise<FeedTest>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): FeedTest {
    return super.attach(address) as FeedTest;
  }
  connect(signer: Signer): FeedTest__factory {
    return super.connect(signer) as FeedTest__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): FeedTestInterface {
    return new utils.Interface(_abi) as FeedTestInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): FeedTest {
    return new Contract(address, _abi, signerOrProvider) as FeedTest;
  }
}
